name: Continuous Integration Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "runs Unit test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: "checkout repository"
    - name: "Install dependencies"
      run: npm ci
    - name: "run tests"
      run: npm run test

  lint:
    name: "run lint"
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
      name: "checkout repository"
    - name: "Install dependencies"
      run: npm ci
    - name: "run lint"
      run: npx standard -v